org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Dependencies
fabric_api_version=0.144.3+26.1

# Mod Properties
mod_id=toomanypaintings
mod_name=Too Many Paintings!
mod_license=ARR
mod_version=26.08.14-26.1-fabric
mod_authors=Axperty
mod_description=A mod that adds even more beautiful paintings to the game.
maven_group=com.axperty
archives_base_name=toomanypaintings