org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.19.4
yarn_mappings=1.19.4+build.1
loader_version=0.14.19

# Dependencies
fabric_version=0.77.0+1.19.4

# Mod Properties
mod_id=toomanypaintings
mod_name=Too Many Paintings!
mod_license=MIT
mod_version=26.08.16-1.19.4-fabric
mod_authors=Axperty
mod_description=A mod that adds even more beautiful paintings to the game.
maven_group=com.axperty
archives_base_name=toomanypaintings